### ISSUE TITLE
Hello, Error while running running your project?

### ISSUE THREAD

**Issue by MohammadAvrahem** [mostafa-mahmoud/sahwaka#109]
Hello,
I got this error when i tried to run your software?

C:\Python27\python.exe C:/Users/Avrahim/PycharmProjects/HyPRec/runtests.py
Traceback (most recent call last):
  File "C:/Users/Avrahim/PycharmProjects/HyPRec/runtests.py", line 27, in <module>
    runtests(sys.argv[1:])
  File "C:/Users/Avrahim/PycharmProjects/HyPRec/runtests.py", line 22, in runtests
    suite.addTest(unittest.defaultTestLoader.loadTestsFromName(test))
  File "C:\Python27\lib\unittest\loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'collaborative_tests'

**Comment by mostafa-mahmoud** [comment]
You are missing the tests folder's prefix in the argument, it should be "tests.collaborative_tests"
` python3` runtests.py tests.collaborative_tests
